
services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
      - PORT=80
    env_file: 
     - backend/.env  # Mova esta linha para o nível do serviço
    depends_on:
      - frontend

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production